### PR TITLE
Update wordpress-startup-script.sh

### PR DESCRIPTION
**Pull request by ezraholm50**

### CODE REVIEW

**Comment by enoch85** [comment]
Have you tested this?

**Comment by ezraholm50** [comment]
Partly please do not merge until I made the final changes. Can't do
anything this weekend pretty busy. Should be done around end of the week or
halfway the week. Will keep you updated.

Op za 21 mei 2016 17:29 schreef Daniel Hansson <notifications@github.com>:

> Have you tested this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/enoch85/wordpress-vm/pull/2#issuecomment-220783878>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by enoch85** [comment]
Please add this if it fails:

echo "You could try to change network settings of this VM to 'Bridged Mode'".
  		echo "If that doesn't help, please try to un-check 'Replicate physical host' in"
  		echo "the network settings of the VM."

**Comment by enoch85** [comment]
@ezraholm50 All the times I've tested since the last network check works, and don't fail - no matter which IP or IFACE you are using. Can you confirm this, and if it works please close this. Thanks!

**Comment by ezraholm50** [comment]
Same here, using the same VAR since the changes, works perfectly!

**Comment by lyncock** [comment]
Doubt counter?

**Pull request closed without merging**
