### PR TITLE
change lets encrypt script to wordpress lets encrypt

### PR DESCRIPTION
**Pull request by ezraholm50**

### CODE REVIEW

**Comment by enoch85** [comment]
This is fix in another way, your solution woulnd't work anyway. Thanks for the heads up!

**Comment by ezraholm50** [comment]
Tell me how, as far as I know this should work, only needs the bash letsencrypt-wp.sh changed somewhere.

**Comment by enoch85** [comment]
Yeah, let's seperate them specifically instead. Thanks!

**Comment by lyncock** [comment]
Anyone doubting?

**Pull request closed without merging**
